version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    # volumes:
    #   - .docker/mysql:/var/lib/mysql

  ordersystem:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 8080:8080
      - 50051:50051
      - 8000:8000

  migrate:
    image: migrate/migrate
    container_name: migrate
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./sql/migrations:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "mysql://root:root@tcp(mysql:3306)/orders",
        "up",
      ]
